QA/Controllers/AnswersController.cs
using Core;
using QA.Model;
using QA.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace QA.Controllers
{
    public class AnswersController : BaseController
    {
        private PostVoter voter;

        public AnswersController(IUnitOfWork uow, PostVoter voter)
        {
            this.voter = voter;
            Uow = uow;
        }

        [Authorize]
        [ValidateInput(false)]
        public ActionResult Create(int questionID, string content)
        {
            var answer = new Answer() { 
                Content = HtmlUtility.SanitizeHtml(content), 
                DatePosted = DateTime.Now,
                VoteCount = 0,
                UserID = Uow.Users.CurrentUserId,
                QuestionID = questionID
            };

            Uow.Answers.Add(answer);
            Uow.Commit();

            var answerViewModel = new AnswerViewModelForQuestionDetailsPage()
            {
                Content = HtmlUtility.SanitizeHtml(content),
                DatePosted = DateTime.Now,
                VoteCount = 0,
                IsAnswerFromCurrentUser = true,
                User = Uow.Users.GetById(Uow.Users.CurrentUserId)
            };

            return PartialView("partial_Answer", answerViewModel);
        }

        public ActionResult Edit(int id)
        {
            var answer = Uow.Answers.GetAll().SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId && i.ID == id);

            if (answer == null)
            {
                return View("PermissionsError");
            }

            AnswerEditViewModel viewModel = new AnswerEditViewModel()
            {
                ID = id,
                Content = answer.Content
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, string content)
        {
            var answer = Uow.Answers.GetAll().SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId && i.ID == id);

            if (answer == null)
            {
                return View("PermissionsError");
            }

            answer.Content = HtmlUtility.SanitizeHtml(content);
            
            Uow.Commit();

          //  return RedirectToAction("Details", "Questions", new { id = answer.QuestionID });
            return Redirect(Url.Action("Details", "Questions", new { id = answer.QuestionID }) + "#" + answer.ID);
        }

        public int PlaceVote(int answerID, int voteType)
        {
            int voteCount = voter.Vote(answerID, (VoteType)voteType);
            return voteCount;
        }

    }
}

QA/Views/Shared/PermissionsError.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Permissions Error";
}

<hgroup class="title">
    <h1 class="error">Error.</h1>
    <h2 class="error">You don't have permissions to do this opperation.</h2>
</hgroup>

QA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Q and A", "Index", "Questions")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Questions", "Index", "Questions")</li>
                            <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
                            <li>@Html.ActionLink("Ask Question", "Create", "Questions")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/qa")
        

        @RenderSection("scripts", required: false)
    </body>
</html>

QA/Views/Shared/partial_Answer.cshtml
@model AnswerViewModelForQuestionDetailsPage
<div class="answer" data-answerid ="@Model.ID">
    <a name="@Model.ID"></a>
    <table>
        <tbody>
            <tr>
                <td class="votecell">
                     <div class="vote">
                        <input type="hidden" value="@Model.ID">
                        <a class="vote-up-off vote-up-answer @(Model.AnswerVoteType == (int)VoteType.Up ? "vote-up-on" : "")" data-answer-id ="@Model.ID">up vote</a>
                        <span id="vote-count-holder-answer-@Model.ID" class="vote-count-post ">@Model.VoteCount</span>
                        <a class="vote-down-off vote-down-answer @(Model.AnswerVoteType == (int)VoteType.Down ? "vote-down-on" : "")" data-answer-id ="@Model.ID">down vote</a>

                    </div>
                </td>
                <td class="answercell">
                     <div class="post-text">
                          @Html.Raw(Model.Content)
                        </div>
                    <div>
                      @*  @Html.ActionLink("Flag", "Flag", "Answers", new { id = Model.ID }, null)  *@
                    @if (Model.IsAnswerFromCurrentUser)
                    {
                      @Html.ActionLink("Edit", "Edit", "Answers", new { id = Model.ID }, null) @*<span> | </span>
                          @Html.ActionLink("Delete", "Edit", "Answers", new { id = Model.ID }, null)  *@
                    }
                    
</div>                    
                    
                    <div class="fr">
                            <div class="user-info">
                                <div>answered @Model.DatePosted.ToNicelyFormattedDateTime()</div>
                                @Html.Partial("partial_UserDetails", Model.User)
                            </div>
                        </div>
                </td>
            </tr>
        </tbody>
    </table>
    
</div>

QA/Views/Shared/partial_Tags.cshtml
@model IEnumerable<QA.Model.Tag>
@foreach (var tag in Model)
{
    <span title="@tag.Description">[@Html.ActionLink(tag.Name, "Details", "Tags", new { id = tag.ID }, null)]</span>
}

QA/Views/Shared/partial_UserDetails.cshtml
@model QA.Model.User
<div class="">
    @Model.Username
</div>
<div class="">
    Questions: @Model.Questions.Count
    Answers: @Model.Answers.Count
</div>