QA/Controllers/QuestionsController.cs
using Core;
using QA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using QA.Model;

namespace QA.Controllers
{
    [Authorize]
    public class QuestionsController : BaseController
    {
        private PostVoter voter;

        public QuestionsController(IUnitOfWork uow, PostVoter voter)
        {
            this.voter = voter;
            Uow = uow;
        }

        [AllowAnonymous]
        public ActionResult Index(string q, int page = 1, int pagesize = 5, string sort = "newest")
        {
            var questions = Uow.Questions.GetAll()
                .Where(i => q == null || i.Title.Contains(q) || i.Content.Contains(q));

            switch (sort.ToEnum<QuestionsSortOrder>(defaultValue: QuestionsSortOrder.Newest))
            {
                case QuestionsSortOrder.Newest:
                    questions = questions.OrderByDescending(i => i.DatePosted);
                    break;
                case QuestionsSortOrder.Votes:
                    questions = questions.OrderByDescending(i => i.VoteCount);
                    break;
                case QuestionsSortOrder.Views:
                    questions = questions.OrderByDescending(i => i.NumberOfViews);
                    break;
            }

            IPagedList<Question> questionsPage = questions.ToPagedList(page, pagesize);

            return View(questionsPage);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(QuestionCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                Question question = new Question()
                {
                    Content = HtmlUtility.SanitizeHtml(model.Content),
                    Title = model.Title,
                    DatePosted = DateTime.Now,
                    VoteCount = 0,
                    NumberOfViews = 0,
                    Status = 1,
                    UserID = Uow.Users.CurrentUserId
                };

                Uow.Questions.Add(question);

                List<string> tags = model.Tags.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries).ToList();

                List<int> tagIDs = Uow.Tags.GetAll().Where(t => tags.Contains(t.Name)).Select(t => t.ID).ToList();

                Uow.Questions.AddQuestionTags(question, tagIDs);

                Uow.Commit();

                return RedirectToAction("Index");
            }
            else
            {
                return View("Create");
            }
        }

        public ActionResult Edit(int id)
        {
            var question = Uow.Questions.GetAll().SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId && i.ID == id);

            if (question == null)
            {
                return View("PermissionsError");
            }

            var viewModel = new QuestionEditViewModel()
            {
                ID = id,
                Title = question.Title,
                Content = question.Content,
                Tags = String.Join(",", question.QuestionsTags.Select(i => i.Tag.Name))
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(QuestionEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var question = Uow.Questions.GetAll().SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId && i.ID == model.ID);

                if (question == null)
                {
                    return RedirectToAction("PermissionsError");
                }

                question.Title = model.Title;
                question.Content = model.Content;

                var questionTags = question.QuestionsTags.ToList();

                foreach (var questionTag in questionTags)
                {
                    Uow.QuestionsTags.Delete(questionTag);
                }

                List<string> tags = model.Tags.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries).ToList();

                List<int> tagIDs = Uow.Tags.GetAll().Where(t => tags.Contains(t.Name)).Select(t => t.ID).ToList();

                Uow.Questions.AddQuestionTags(question, tagIDs);

                Uow.Commit();

                return RedirectToAction("Index");
            }
            else
            {
                return View("Edit", new { id = model.ID });
            }
        }

        [AllowAnonymous]
        public ActionResult Details(int id, int page = 1, string answerSort = "votes")
        {
            var question = Uow.Questions.GetById(id);
            question.NumberOfViews++;
            Uow.Commit();

            // this is a big mess, fix it later on
            IEnumerable<Answer> answers = Uow.Answers.GetAll().Where(i => i.QuestionID == id);

            if (answerSort == "oldest")
            {
                answers = answers.OrderByDescending(i => i.DatePosted).ToList();
            }
            else
            {
                answers = answers.OrderByDescending(i => i.VoteCount).ToList();
            }

            var questionVoteType = question.Votes.SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId);

            List<AnswerViewModelForQuestionDetailsPage> partialAnswers = new List<AnswerViewModelForQuestionDetailsPage>();

            foreach (var answer in answers)
            {
                var answerVoteType = answer.Votes.SingleOrDefault(i => i.UserID == Uow.Users.CurrentUserId);

                partialAnswers.Add(new AnswerViewModelForQuestionDetailsPage()
                {
                    ID = answer.ID,
                    Content = answer.Content,
                    VoteCount = answer.VoteCount,
                    DatePosted = answer.DatePosted,
                    User = answer.User,
                    AnswerVoteType = (answerVoteType != null) ? answerVoteType.Vote : 0,
                    IsAnswerFromCurrentUser = answer.UserID == Uow.Users.CurrentUserId
                });

            }

            QuestionDetailsViewModel viewModel = new QuestionDetailsViewModel()
            {
                ID = question.ID,
                Question = question,
                QuestionVoteType = questionVoteType != null ? questionVoteType.Vote : 0,
                Answers = partialAnswers.ToPagedList(page, 5)
            };

            return View(viewModel);
        }



        public int PlaceVote(int questionID, int voteType)
        {
            int voteCount = voter.Vote(questionID, (VoteType)voteType);
            return voteCount;
        }
    }
}

QA/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core;
using QA.Model;

namespace QA.Controllers
{
    [Authorize(Roles="Admin")]
    public class TagsController : Controller
    {
        private Entities db = new Entities();

        //
        // GET: /Tag/
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        [AllowAnonymous]
        public ActionResult GetTags(string term)
        {
            return Json(db.Tags.Where(t => t.Name.Contains(term)).Select(t => t.Name).ToList(), JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Tag/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tag/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tag/Create

        [HttpPost]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        //
        // GET: /Tag/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Edit/5

        [HttpPost]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //
        // GET: /Tag/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

QA/Views/Questions/Create.cshtml
@model QA.QuestionCreateViewModel

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/jquery.tagsinput.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery.ui.autocomplete.css" rel="stylesheet" />
<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>QuestionCreateViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content, new { cols = "20", rows = "20"  })
            @Html.ValidationMessageFor(model => model.Content)
        </div>
           <div class="editor-label">
            Tags
        </div>
        <div class="editor-field">
           @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
  @*  @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")*@
    <script src="~/Scripts/lib/jquery.tagsinput.js"></script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: "#Content",
            menubar: false,
            //  plugins: "code",
            toolbar: "undo redo | bold italic | numlist bullist | indent | code"

        });

        $('#Tags').tagsInput({
            autocomplete_url: '@Url.Action("GetTags","Tags")'
        });

        var $answerForm = $('.main-content form');

        $answerForm.submit(function () {

            tinymce.get('user-answer-content').save();

            //$.post("/Answer/Create", $answerForm.serialize(), function (data) {
            //    //console.log(data);
            //    $('#answers').append(data);
            //    $answerForm.find('textarea').val('');
            //});

            return true;
        });

    </script>
}

QA/Views/Questions/Details.cshtml
@model  QA.QuestionDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>@Html.ActionLink(Model.Question.Title, "Details", "Questions", new { id = Model.ID, slug = Model.Question.Title.ToSeoUrl() }, null)</h2>

<input type="hidden" id="current-user-username" value="@HttpContext.Current.User.Identity.Name"/>
<input type="hidden" id="question-id" value="@Model.ID" />
<div class="question">
    <table>
        <tbody>
            <tr>
                <td class="votecell">

                    <div class="vote">
                        <input type="hidden" value="@Model.ID">
                        <a id="vote-up" class="vote-up-off @(Model.QuestionVoteType == (int)VoteType.Up ? "vote-up-on" : "")">up vote</a>
                        <span id="vote-count-holder" class="vote-count-post ">@Model.Question.VoteCount</span>
                        <a id="vote-down" class="vote-down-off @(Model.QuestionVoteType == (int)VoteType.Down ? "vote-down-on" : "")">down vote</a>



                    </div>
                </td>
                <td class="postcell">
                    <div>
                        <div class="post-text">
                            @Html.Raw(Model.Question.Content)
                        </div>
                        <div class="post-taglist">@Html.Partial("partial_Tags", Model.Question.QuestionsTags.Select(t => t.Tag))</div>
                        <div class="fr">
                            <div class="user-info">
                                <div>asked @Model.Question.DatePosted.ToNicelyFormattedDateTime()</div>
                                @Html.Partial("partial_UserDetails", Model.Question.User)
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

</div>

@if (Model.Question.User.Username == HttpContext.Current.User.Identity.Name)
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID })
    </p>
}

<div id="answers" style="border: 1px solid black">

    @{
        bool showAnswerPager = Model.Question.Answers.Count() > 5;
        int answerCount = Model.Question.Answers.Count();
        string answerCountText = answerCount == 1 ? "1 Answer" : answerCount + " Answers";
    }


    <div id="answer-header">
        <div class="subheader">
            <h3>@answerCountText </h3>
            @if (Model.Question.Answers.Count() > 1)
            {
                <div id="tabs">
                    @Html.ActionLink("oldest", "Details", "Questions",
                new { id = Model.ID, slug = Model.Question.Title.ToSeoUrl(), answersort = "oldest" },
                new { @class = (Request.QueryString["answersort"] == "oldest") ? "youarehere" : "" })

                    @Html.ActionLink("votes", "Details", "Questions",
                new { id = Model.ID, slug = Model.Question.Title.ToSeoUrl(), answersort = "votes" },
                new { @class = (Request.QueryString["answersort"] == "votes" || Request.QueryString["answersort"] == null) ? "youarehere" : "" })
                </div>
            }
        </div>
    </div>

    @foreach (var answer in Model.Answers)
    {
        @Html.Partial("partial_Answer", answer);
    }
    @if (showAnswerPager)
    {
        <div class="pager">

            @Html.PagedListPager(Model.Answers,
                                    page => Url.Action("Details", "Questions",
                                                        new
                                                        {
                                                            page = page,
                                                            id = Model.ID,
                                                            slug = Model.Question.Title.ToSeoUrl(),
                                                            answersort = Request.QueryString["answersort"]
                                                        }),
                                    PagedListRenderOptions.OnlyShowFivePagesAtATime)
        </div>
       
    }
</div>

@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    

<div style="border: 1px solid red">
    Enter your answer:
  <form action="/Answer/Create" id="user-answer-form">
      <input type="hidden" name="questionID" value="@Model.ID" />
      <textarea id="user-answer-content" name="content" rows="10"> </textarea>
      <input type="submit" name="answer" />
  </form>

</div>
}
else
{
    <div>Please @Html.ActionLink("log in", "LogIn", "Account",
    new { returnUrl = Url.Action("Details", "Questions", new { id = Model.ID, slug = Model.Question.Title.ToSeoUrl() }) },
    null) to vote</div>
}

@section scripts{
    <script id="answerTemplate" type="text/x-handlebars-template">
        <div class="answer" data-answerid="{{answerId}}">
            <a name="{{answerId}}"></a>
            <table>
                <tbody>
                    <tr>
                        <td class="votecell">
                            <div class="vote">
                                <input type="hidden" value="{{answerId}}">
                                <a class="vote-up-off vote-up-answer" data-answer-id="{{answerId}}">up vote</a>
                                <span id="vote-count-holder-answer-{{answerId}}" class="vote-count-post ">{{voteCount}}</span>
                                <a class="vote-down-off vote-down-answer" data-answer-id="{{answerId}}">down vote</a>

                            </div>
                        </td>
                        <td class="answercell">
                            <div class="post-text">
                                
                                {{{content}}}
                            </div>
                    
         {{#if showEditLink }}
            <a href="{{edithref}}">Edit</a>
         {{/if}} 
        </div>
                    <div class="fr">
                            <div class="user-info">
                                <div>answered {{dateAnswered}}</div>
                                <div class="">
                                    {{username}}
                                </div>
                                <div class="">
                                    Questions: {{questionCount}}
                                    Answers: {{answerCount}}
                                </div>
                            </div>
                        </div>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>

        tinymce.init({
            selector: "#user-answer-content",
            menubar: false,
            //  plugins: "code",
            toolbar: "undo redo | bold italic | numlist bullist | indent | code"

        });
    </script>
    <script src="~/Scripts/app/voter.js"></script>

    @if (false/*Globals.UseSignalR*/)
    {
        
        <script src="~/Scripts/lib/jquery.signalR-1.0.1.min.js"></script>
        <script src="/signalr/hubs"></script>
        <script src="~/Scripts/lib/handlebars.js"></script>
        <script src="~/Scripts/app/details-signalR.js"></script>
       
    }
    else
    {
        <script src="~/Scripts/app/details.js"></script>
    }
}

QA/Views/Questions/Edit.cshtml
@model QA.QuestionEditViewModel

@{
    ViewBag.Title = "Edit";
}
<link href="~/Content/jquery.tagsinput.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery.ui.autocomplete.css" rel="stylesheet" />
<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>QuestionEditViewModel</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content, new { cols = "20", rows = "20"  })
            @Html.ValidationMessageFor(model => model.Content)
        </div>

            <div class="editor-label">
            Tags
        </div>
        <div class="editor-field">
           @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>


        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {


    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: "#Content",
            menubar: false,
            //  plugins: "code",
            toolbar: "undo redo | bold italic | numlist bullist | indent | code"

        });

   
        var $answerForm = $('.main-content form');
        $answerForm.submit(function () {

            tinymce.get('user-answer-content').save();

            //$.post("/Answer/Create", $answerForm.serialize(), function (data) {
            //    //console.log(data);
            //    $('#answers').append(data);
            //    $answerForm.find('textarea').val('');
            //});

            return true;
        });

    </script>

    <script src="~/Scripts/lib/jquery.tagsinput.js"></script>
    <script>
        $('#Tags').tagsInput({
            autocomplete_url: '@Url.Action("GetTags","Tags")'
        });
    </script>
}

QA/Views/Questions/Index.cshtml
@model IPagedList<QA.Model.Question>

@{
    ViewBag.Title = "Newest questions - Q and A";
}

<form method="get" action="@Url.Action("Index")" data-ajax-enabled="false" data-target="#questions">

    <input type="search" name="q" />
    <input type="submit" value="Search By Title and Content" />
</form>

<div id="mainbar">
    <div class="subheder" style="border:1px solid green;">
        <div id="tabs">
@*            <a href="@(Url.Action("Index","Questions") + "?" + Request.QueryString.ToString() + "sort=newest")">newest 2</a> 
            <a href="@(Url.Action("Index","Questions") + "?" + Request.QueryString.ToString() + "sort=votes")">votes 2</a> 
            <a href="@(Url.Action("Index","Questions") + "?" + Request.QueryString.ToString() + "sort=views")">views 2</a> *@
            @Html.ActionLink("newest", "Index", "Questions", new
                            {
                                sort = "newest",
                                page = Request.QueryString["page"] ?? "1",
                                pagesize = Request.QueryString["pagesize"] ?? "5",
                                q = Request.QueryString["q"]
                            }, null)
            @Html.ActionLink("votes", "Index", "Questions", new
                            {
                                sort = "votes",
                                page = Request.QueryString["page"] ?? "1",
                                pagesize = Request.QueryString["pagesize"] ?? "5",
                                q = Request.QueryString["q"]
                            }, null)
            @Html.ActionLink("views", "Index", "Questions", new
                            {
                                sort = "views",
                                page = Request.QueryString["page"] ?? "1",
                                pagesize = Request.QueryString["pagesize"] ?? "5",
                                q = Request.QueryString["q"]
                            }, null)
        </div>
    </div>
    <div id="questions">
        @foreach (var item in Model)
        {
            <div class="question-summary">
                <div class="statscontainer">
                    <div class="stats">
                        <div class="vote">
                            <div class="votes">
                                <div class="vote-count-post">
                                    <strong>@item.VoteCount</strong>
                                </div>
                                <div>votes</div>
                            </div>
                        </div>
                        <div class="status @Html.GetClassForQuestionStatus(item.Status, item.Answers.Count())">
                            <strong>@item.Answers.Count()</strong> answers
                        </div>
                    </div>

                    <div class="views">@item.NumberOfViews views</div>
                </div>
                <div class="summary">
                    <h3>@Html.ActionLink(item.Title, "Details", "Questions", new { id = item.ID, slug = item.Title.ToSeoUrl() }, null)</h3>
                    <div class="excerpt">@Html.Truncate(item.Content.RemoveHtmlTags(), 200)</div>
                    <div class="tags">@Html.Partial("partial_Tags", item.QuestionsTags.Select(i => i.Tag))</div>
                    <div class="fr">
                        <div class="user-info">
                            <div>asked @item.DatePosted.ToNicelyFormattedDateTime()</div>
                            @Html.Partial("partial_UserDetails", item.User)
                        </div>
                    </div>
                    @if (item.User.Username == HttpContext.Current.User.Identity.Name)
                    {
                     
                    <div>@Html.ActionLink("Edit", "Edit", "Questions", new { id = item.ID }, null)</div>   
                    }
                    else
                    {
                    
                    <div> No Edit</div>
                    }
                </div>
            </div>
        }
    </div>
    <div class="cbt"></div>
    <div class="pager fl" data-target="#questions">
        @Html.PagedListPager(Model,
                            page => Url.Action("Index", new
                            {
                                page = page,
                                sort = Request.QueryString["sort"],
                                pagesize = Request.QueryString["pagesize"] ?? "5",
                                q = Request.QueryString["q"]
                            }),
                            PagedListRenderOptions.OnlyShowFivePagesAtATime)

    </div>
    <div class="page-sizer fr">
        @PageSizer("Index", "Questions", Model.PageNumber, Request.QueryString["pagesize"], Request.QueryString["q"], Request.QueryString["sort"], new List<int> { 5, 6, 7 })


        @*  @Html.ActionLink("2", "Index", "Question", new { page = Model.PageNumber, pagesize = 2, q = Request.QueryString["q"] }, 
        new {@class= "page-numbers" + ((Request.QueryString["pagesize"] == "2" || Request.QueryString["pagesize"] == null) ? " current" : "" )})
        
        @Html.ActionLink("3", "Index", "Question", new { page = Model.PageNumber, pagesize = 3, q = Request.QueryString["q"] }, 
        new {@class= "page-numbers" + ((Request.QueryString["pagesize"] == "3") ? " current" : "" )})
        
        @Html.ActionLink("4", "Index", "Question", new { page = Model.PageNumber, pagesize = 4, q = Request.QueryString["q"] }, 
        new {@class= "page-numbers" + ((Request.QueryString["pagesize"] == "4") ? " current" : "" )})*@
    </div>
</div>


@helper PageSizer(string action, string controller, int pageNumber, string queryPageSize, string q, string sort, List<int> sizeNumbers)
{
    
    string firstNumber = sizeNumbers.First().ToString();
     
    @Html.ActionLink(firstNumber, action, controller,
        new { page = pageNumber, pagesize = firstNumber, sort = sort, q = q },
        new { @class = "page-numbers" + ((queryPageSize == firstNumber || queryPageSize == null) ? " current" : "") })

    for (int i = 1; i < sizeNumbers.Count; i++)
    {
    @Html.ActionLink(sizeNumbers[i].ToString(), action, controller,
        new { page = pageNumber, pagesize = sizeNumbers[i], sort = sort, q = q },
        new { @class = "page-numbers" + ((queryPageSize == sizeNumbers[i].ToString()) ? " current" : "") })
 
    }
}